# CodeRabbit Configuration for Information Reconstructionism
version: "1"
language: "en-US"
early_access: false

# Review Settings
reviews:
  # Request incremental reviews on every push
  request_changes_workflow: true
  
  # High-level summary of changes
  high_level_summary: true
  
  # Generate poems or creative content (set to false for professional reviews)
  poem: false
  
  # Enable review status checks
  review_status: true
  
  # Collapse generated summary details by default
  collapse_walkthrough: false
  
  # Automatically approve dependency updates
  auto_review:
    enabled: true
    drafts: false
  
  # Path-specific instructions
  path_instructions:
    - path: "paper/**"
      instructions: |
        - Focus on mathematical rigor and clarity
        - Ensure citations follow academic standards
        - Verify mathematical proofs are well-structured
        - Check for consistency in terminology
        - Validate equations and formulas
        - Ensure theoretical claims are properly supported
        
    - path: "infrastructure/setup/**"
      instructions: |
        - Check for proper GPU resource management
        - Verify ArangoDB connection patterns and transactions
        - Ensure proper error handling for arXiv data processing
        - Validate batch processing efficiency
        - Check for proper checkpoint and recovery mechanisms
        - Ensure atomic transaction integrity
        
    - path: "infrastructure/irec_infrastructure/**"
      instructions: |
        - Verify proper abstraction and modularity
        - Check for proper async/await patterns
        - Ensure GPU memory management is optimal
        - Validate embedding batch sizes and efficiency
        - Check for proper error propagation
        - Ensure proper logging and monitoring
        
    - path: "experiments/**"
      instructions: |
        - Ensure reproducibility of experiments
        - Check for proper data handling and cleanup
        - Verify statistical validity of results
        - Ensure proper separation of concerns
        - Validate experiment configurations
        
    - path: "*.py"
      instructions: |
        - Follow PEP 8 style guidelines
        - Use type hints where appropriate
        - Ensure proper docstrings for public functions
        - Check for proper exception handling
        - Verify no hardcoded paths or credentials
  
  # File patterns to exclude from reviews
  path_filters:
    - "**/*.lock"
    - "**/node_modules/**"
    - "**/__pycache__/**"
    - "**/venv/**"
    - "**/.mypy_cache/**"
    - "**/.pytest_cache/**"
    - "**/logs/**"
    - "**/data/**"
    - "**/*.db"
    - "**/checkpoints/**"
    - "**/*.done"
    - "**/*.log"
    - "**/models/*.pth"
    - "**/*.mdb"

# Note: The following configurations from the original file are not supported by CodeRabbit:
# - issue_handling: Use GitHub Actions or CI/CD for issue creation
# - review_checklist: Implement in CI/CD pipeline
# - batch_processing: Not a valid CodeRabbit configuration
# - quality_gates: Use external quality tools (SonarQube, etc.)
#
# For quality gates and issue management, consider using:
# - GitHub Actions for automated issue creation
# - Pre-commit hooks for code quality checks
# - CI/CD pipelines for coverage and complexity metrics